### ISSUE TITLE
PUT or PATCH requests return error on "("

### ISSUE THREAD

**Issue by ramifi** [jaystack/odata-v4-server-mongodb-example#13]
Hi
When I am trying to send PUT request like this: http://laptop:3000/Offers(595b9f0d9af14410c44e4ee7)

Unexpected character at 7 - which is "("

I am getting this error:

   "error": {
        "code": 500,
        "message": "Unexpected character at 7",
        "stack": "Error: Unexpected character at 7\n    at c:\\dev\\sag\\xact-api\\node_modules\\odata-v4-parser\\lib\\parser.js:20:19\n    at Object.odataUri (c:\\dev\\sag\\xact-api\\node_modules\\odata-v4-parser\\lib\\parser.js:36:77)\n    at ODataProcessor (c:\\dev\\sag\\xact-api\\node_modules\\odata-v4-server\\build\\lib\\processor.js:416:31)\n    at Function.createProcessor (c:\\dev\\sag\\xact-api\\node_modules\\odata-v4-server\\build\\lib\\server.js:176:16)\n    at c:\\dev\\sag\\xact-api\\node_modules\\odata-v4-server\\build\\lib\\server.js:73:38\n    at Layer.handle [as handle_request] (c:\\dev\\sag\\xact-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (c:\\dev\\sag\\xact-api\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at c:\\dev\\sag\\xact-api\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (c:\\dev\\sag\\xact-api\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (c:\\dev\\sag\\xact-api\\node_modules\\express\\lib\\router\\index.js:275:10)"

**Comment by ramifi** [comment]
FIXXED:
I had to write it as this: http://laptop:3000/Offers('595b9f0d9af14410c44e4ee7')
