### ISSUE TITLE
Cannot get sample to run

### ISSUE THREAD

**Issue by nigel-dewar** [jaystack/odata-v4-server-mongodb-example#15]
Hi There, I am having trouble getting sample to run.

Is there anything one must install first before running, like typescript ???

Here is what I am getting from the log file when trying to run. I have the latest stable version of Node and NPM installed, mongo is running on standard port (unsecured - no password required )

info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle odata-v4-server-mongodb-example@0.1.0~prestart: odata-v4-server-mongodb-example@0.1.0
6 silly lifecycle odata-v4-server-mongodb-example@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle odata-v4-server-mongodb-example@0.1.0~start: odata-v4-server-mongodb-example@0.1.0
8 verbose lifecycle odata-v4-server-mongodb-example@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle odata-v4-server-mongodb-example@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\_tests\odata-v4-server-mongodb-example\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Users\dewarn\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\dewarn\AppData\Local\Programs\Fiddler
10 verbose lifecycle odata-v4-server-mongodb-example@0.1.0~start: CWD: C:\_tests\odata-v4-server-mongodb-example
11 silly lifecycle odata-v4-server-mongodb-example@0.1.0~start: Args: [ '/d /s /c', 'node .' ]
12 silly lifecycle odata-v4-server-mongodb-example@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle odata-v4-server-mongodb-example@0.1.0~start: Failed to exec start script
14 verbose stack Error: odata-v4-server-mongodb-example@0.1.0 start: `node .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid odata-v4-server-mongodb-example@0.1.0
16 verbose cwd C:\_tests\odata-v4-server-mongodb-example
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error odata-v4-server-mongodb-example@0.1.0 start: `node .`
22 error Exit status 1
23 error Failed at the odata-v4-server-mongodb-example@0.1.0 start script 'node .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the odata-v4-server-mongodb-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs odata-v4-server-mongodb-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls odata-v4-server-mongodb-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any assistance greatly appreciated

**Comment by nigel-dewar** [comment]
No worries, figured it out
