### ISSUE TITLE
Unable to make this work

### ISSUE THREAD

**Issue by ericsolberg** [jaystack/odata-v4-server-mongodb-example#19]
I've been trying to work through this, as well as similar tutorials on jaydata.org. It seems that the tutorials may not be complete, in terms of stand-alone instructions-- they seem to require extra steps that aren't covered. I'm an experienced SW architect, but I am new to NodeJS. For example - the instructions start with **npm run build** -- but I do believe you need to do **npm install** first, correct? Here's the specific steps I've followed, and the errors I'm encountering.

I have node 8.11.2 with npm 5.6.0. I've installed MongoDB on my Mac. Using MongoHub, I've created a database called northwind, to hopefully work with this tutorial. It's not clear to me what else I need to set up- I've tried also creating Product and Category collections, but this didn't make a difference. At this point I'm not sure that the database connection is the problem, but I'm also unsure if the database is setup properly. My mongo is on 127.0.0.1:27017.

These are the specific steps from there:
```
git clone https://github.com/jaydata/jaydata.org-examples.git
cd odata-v4-server-mongodb-example
npm install
npm run build
npm start
```
Result is:
```
_stream_duplex.js:73
    return this._writableState.highWaterMark;
                               ^

TypeError: Cannot read property 'highWaterMark' of undefined
    at ODataServer.get (_stream_duplex.js:73:32)
    at propNames.forEach (/Users/i809433/NodeData/odata-v4-server-mongodb-example/node_modules/odata-v4-server/build/lib/metadata.js:297:49)
    at Array.forEach (<anonymous>)
    at Object.createMetadataJSON (/Users/i809433/NodeData/odata-v4-server-mongodb-example/node_modules/odata-v4-server/build/lib/metadata.js:295:15)
    at Function.$metadata (/Users/i809433/NodeData/odata-v4-server-mongodb-example/node_modules/odata-v4-server/build/lib/server.js:187:137)
    at Function.document (/Users/i809433/NodeData/odata-v4-server-mongodb-example/node_modules/odata-v4-server/build/lib/server.js:190:77)
    at Function.create (/Users/i809433/NodeData/odata-v4-server-mongodb-example/node_modules/odata-v4-server/build/lib/server.js:234:19)
    at Object.<anonymous> (/Users/i809433/NodeData/odata-v4-server-mongodb-example/lib/ts/index.js:5:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
I see that a dockerized version is provided as well, and I thought that may help me get past this, so I tried:
```
npm run docker-build
npm run docker-run
```
Result:
```
docker: Error response from daemon: could not get container for mongo: No such container: mongo.
See 'docker run --help'.
npm ERR! code ELIFECYCLE
npm ERR! errno 125
npm ERR! odata-v4-server-mongodb-example@0.1.0 docker-run: `docker run --name odata-v4-server-mongodb-example --link mongo:mongo -p 3000:3000 -d odata-v4-server-mongodb-example`
npm ERR! Exit status 125
npm ERR! 
npm ERR! Failed at the odata-v4-server-mongodb-example@0.1.0 docker-run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i809433/.npm/_logs/2018-06-07T23_56_09_032Z-debug.log
```
It makes sense that this is looking for a docker instance named mongo, with the mongo port exported. Once I ran this, the docker container launched properly, but still there was no OData server on port 3000. I entered the docker container and tried running **node .** manually and I get the same error message "TypeError: Cannot read property 'highWaterMark' of undefined ..."

I've tried to debug- using console.log statements I have traced execution into metadata.js, right at the line mentioned in the error log above - the propNames.forEach statement. But I can't really tell what is going on here enough to debug it. 

Any pointers to get me over missing steps in the tutorial, or anything I may be doing wrong would be very helpful.

**Comment by ericsolberg** [comment]
Note that I tried this with the postgres example as well and get the same error.

**Comment by atul221282** [comment]
I tried with ms sql example and got the same error of **highWaterMark**

**Comment by Steentje86** [comment]
I tried it also with mssql example and get same error of highWaterMark

**Comment by AsCEX** [comment]
how to resolve this error of highWaterMark? does anyone solve this? please help.

**Comment by charles-dejager** [comment]
Ensure your odata-v4-server is at least on 0.2.13 .   package.json dependancy "odata-v4-server": "^0.2.13",

**Comment by madfist** [comment]
The error comes from `odata-v4-server/lib/metadata.ts:39` to get the controllers the code recursively goes through all the keys of the prototypes ending up in `node.OutputStream`. I foyu change it to `let propNames = Object.getOwnPropertyNames(server.prototype)` it works.
Strangely all examples throw this error, but when I include it in my project, it could be some kind of `tsconfig.json` differnece that I could not find yet.

**Comment by ClarkDennison** [comment]
Did the above, now getting an error:

`node_modules/@types/connect/index.d.ts:21:42 - error TS2689: Cannot extend an interface 'http.IncomingMessage'. Did you mean 'implements'?

21     export class IncomingMessage extends http.IncomingMessage {
                                            ~~~~~~~~~~~~~~~~~~~~ `

**Comment by ClarkDennison** [comment]
Overcame the above error with 

npm i @types/node@latest

Which I found here.. 

https://stackoverflow.com/questions/59903597/cannot-extend-an-interface-http-incomingmessage-did-you-mean-implements

Now the next issue..

`node_modules/odata-v4-server/build/lib/processor.d.ts:21:22 - error TS2415: Class 'ODataProcessor' incorrectly extends base class 'Transform'.
  Property '_flush' is protected in type 'ODataProcessor' but public in type 'Transform'.

21 export declare class ODataProcessor extends Transform { `

**Comment by ClarkDennison** [comment]
I did get this to work finally by going into the modules directory and updating the processor.ts file to make these public instance of protected. Started working after this last fix.
